/*
Package internal GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package internal

import _ "embed"

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v *Builder[M]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Source":
			return []string{}, true
		case "TableJoins":
			return []string{}, true
		case "Orders":
			return []string{}, true
		case "Projects":
			return []string{}, true
		case "DefaultProjects":
			return []string{}, true
		case "DistinctOn":
			return []string{}, true
		case "Pager":
			return []string{}, true
		case "Additions":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(&v.Flag, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (*DeleteType) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (v *Mutation[M]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ForDelete":
			return []string{}, true
		case "ForUpdate":
			return []string{}, true
		case "OmitZero":
			return []string{}, true
		case "From":
			return []string{}, true
		case "StrictColumn":
			return []string{}, true
		case "OmitZeroExclude":
			return []string{}, true
		case "Assignments":
			return []string{}, true
		case "Values":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *Seed) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.Flag, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (*StmtPatcherFunc[M]) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
