/*
Package dal GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package dal

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Database) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{
				"Endpoint of database",
			}, true
		case "EnableMigrate":
			return []string{
				"auto migrate before run",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (DeleteFunc) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (OptionFunc) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
