/*
Package filter GENERATED BY gengo:filter 
DON'T EDIT THIS FILE
*/
package filter

import (
	github_com_octohelm_storage_pkg_dal "github.com/octohelm/storage/pkg/dal"
	github_com_octohelm_storage_pkg_dal_compose "github.com/octohelm/storage/pkg/dal/compose"
	github_com_octohelm_storage_pkg_datatypes "github.com/octohelm/storage/pkg/datatypes"
	github_com_octohelm_storage_pkg_filter "github.com/octohelm/storage/pkg/filter"
	github_com_octohelm_storage_testdata_model "github.com/octohelm/storage/testdata/model"
)

type UserByID struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	ID *github_com_octohelm_storage_pkg_filter.Filter[uint64] `name:"user~id,omitempty" in:"query"`
}

func (f *UserByID) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.ID, f.ID)
}

func (f *UserByID) ApplyMutation(m github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User] {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyMutationFromFilter(m, github_com_octohelm_storage_testdata_model.UserT.ID, f.ID)
}

type UserByName struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按 姓名 筛选
	Name *github_com_octohelm_storage_pkg_filter.Filter[string] `name:"user~name,omitempty" in:"query"`
}

func (f *UserByName) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.Name, f.Name)
}

func (f *UserByName) ApplyMutation(m github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User] {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyMutationFromFilter(m, github_com_octohelm_storage_testdata_model.UserT.Name, f.Name)
}

type UserByNickname struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	Nickname *github_com_octohelm_storage_pkg_filter.Filter[string] `name:"user~nickname,omitempty" in:"query"`
}

func (f *UserByNickname) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.Nickname, f.Nickname)
}

func (f *UserByNickname) ApplyMutation(m github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User] {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyMutationFromFilter(m, github_com_octohelm_storage_testdata_model.UserT.Nickname, f.Nickname)
}

type UserByAge struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	Age *github_com_octohelm_storage_pkg_filter.Filter[int64] `name:"user~age,omitempty" in:"query"`
}

func (f *UserByAge) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.Age, f.Age)
}

func (f *UserByAge) ApplyMutation(m github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User] {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyMutationFromFilter(m, github_com_octohelm_storage_testdata_model.UserT.Age, f.Age)
}

type UserByCreatedAt struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	CreatedAt *github_com_octohelm_storage_pkg_filter.Filter[github_com_octohelm_storage_pkg_datatypes.Datetime] `name:"user~createdAt,omitempty" in:"query"`
}

func (f *UserByCreatedAt) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.CreatedAt, f.CreatedAt)
}

func (f *UserByCreatedAt) ApplyMutation(m github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User] {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyMutationFromFilter(m, github_com_octohelm_storage_testdata_model.UserT.CreatedAt, f.CreatedAt)
}

type UserByDeletedAt struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	DeletedAt *github_com_octohelm_storage_pkg_filter.Filter[int64] `name:"user~deletedAt,omitempty" in:"query"`
}

func (f *UserByDeletedAt) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.DeletedAt, f.DeletedAt)
}

func (f *UserByDeletedAt) ApplyMutation(m github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.User] {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyMutationFromFilter(m, github_com_octohelm_storage_testdata_model.UserT.DeletedAt, f.DeletedAt)
}

type OrgByID struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.Org]

	// 按  筛选
	ID *github_com_octohelm_storage_pkg_filter.Filter[uint64] `name:"org~id,omitempty" in:"query"`
}

func (f *OrgByID) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.OrgT.ID, f.ID)
}

func (f *OrgByID) ApplyMutation(m github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.Org]) github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.Org] {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyMutationFromFilter(m, github_com_octohelm_storage_testdata_model.OrgT.ID, f.ID)
}

type OrgByName struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.Org]

	// 按  筛选
	Name *github_com_octohelm_storage_pkg_filter.Filter[string] `name:"org~name,omitempty" in:"query"`
}

func (f *OrgByName) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.OrgT.Name, f.Name)
}

func (f *OrgByName) ApplyMutation(m github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.Org]) github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.Org] {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyMutationFromFilter(m, github_com_octohelm_storage_testdata_model.OrgT.Name, f.Name)
}

type OrgByCreatedAt struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.Org]

	// 按  筛选
	CreatedAt *github_com_octohelm_storage_pkg_filter.Filter[github_com_octohelm_storage_pkg_datatypes.Datetime] `name:"org~createdAt,omitempty" in:"query"`
}

func (f *OrgByCreatedAt) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.OrgT.CreatedAt, f.CreatedAt)
}

func (f *OrgByCreatedAt) ApplyMutation(m github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.Org]) github_com_octohelm_storage_pkg_dal.Mutation[github_com_octohelm_storage_testdata_model.Org] {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyMutationFromFilter(m, github_com_octohelm_storage_testdata_model.OrgT.CreatedAt, f.CreatedAt)
}
