/*
Package filter GENERATED BY gengo:filter 
DON'T EDIT THIS FILE
*/
package filter

import (
	github_com_octohelm_storage_pkg_dal "github.com/octohelm/storage/pkg/dal"
	github_com_octohelm_storage_pkg_dal_compose "github.com/octohelm/storage/pkg/dal/compose"
	github_com_octohelm_storage_pkg_datatypes "github.com/octohelm/storage/pkg/datatypes"
	github_com_octohelm_storage_pkg_filter "github.com/octohelm/storage/pkg/filter"
	github_com_octohelm_storage_pkg_sqlpipe "github.com/octohelm/storage/pkg/sqlpipe"
	github_com_octohelm_storage_pkg_sqlpipe_filter "github.com/octohelm/storage/pkg/sqlpipe/filter"
	github_com_octohelm_storage_testdata_model "github.com/octohelm/storage/testdata/model"
)

type UserByID struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	ID *github_com_octohelm_storage_pkg_filter.Filter[github_com_octohelm_storage_testdata_model.UserID] `name:"user~id,omitempty" in:"query"`
}

func (f *UserByID) OperatorType() github_com_octohelm_storage_pkg_sqlpipe.OperatorType {
	return github_com_octohelm_storage_pkg_sqlpipe.OperatorFilter
}

func (f *UserByID) Next(src github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User] {
	return src.Pipe(github_com_octohelm_storage_pkg_sqlpipe_filter.AsWhere(github_com_octohelm_storage_testdata_model.UserT.ID, f.ID))
}

func (f *UserByID) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.ID, f.ID)
}

type UserByName struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按 姓名 筛选
	Name *github_com_octohelm_storage_pkg_filter.Filter[string] `name:"user~name,omitempty" in:"query"`
}

func (f *UserByName) OperatorType() github_com_octohelm_storage_pkg_sqlpipe.OperatorType {
	return github_com_octohelm_storage_pkg_sqlpipe.OperatorFilter
}

func (f *UserByName) Next(src github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User] {
	return src.Pipe(github_com_octohelm_storage_pkg_sqlpipe_filter.AsWhere(github_com_octohelm_storage_testdata_model.UserT.Name, f.Name))
}

func (f *UserByName) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.Name, f.Name)
}

type UserByNickname struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	Nickname *github_com_octohelm_storage_pkg_filter.Filter[string] `name:"user~nickname,omitempty" in:"query"`
}

func (f *UserByNickname) OperatorType() github_com_octohelm_storage_pkg_sqlpipe.OperatorType {
	return github_com_octohelm_storage_pkg_sqlpipe.OperatorFilter
}

func (f *UserByNickname) Next(src github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User] {
	return src.Pipe(github_com_octohelm_storage_pkg_sqlpipe_filter.AsWhere(github_com_octohelm_storage_testdata_model.UserT.Nickname, f.Nickname))
}

func (f *UserByNickname) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.Nickname, f.Nickname)
}

type UserByAge struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	Age *github_com_octohelm_storage_pkg_filter.Filter[int64] `name:"user~age,omitempty" in:"query"`
}

func (f *UserByAge) OperatorType() github_com_octohelm_storage_pkg_sqlpipe.OperatorType {
	return github_com_octohelm_storage_pkg_sqlpipe.OperatorFilter
}

func (f *UserByAge) Next(src github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User] {
	return src.Pipe(github_com_octohelm_storage_pkg_sqlpipe_filter.AsWhere(github_com_octohelm_storage_testdata_model.UserT.Age, f.Age))
}

func (f *UserByAge) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.Age, f.Age)
}

type UserByCreatedAt struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	CreatedAt *github_com_octohelm_storage_pkg_filter.Filter[github_com_octohelm_storage_pkg_datatypes.Datetime] `name:"user~createdAt,omitempty" in:"query"`
}

func (f *UserByCreatedAt) OperatorType() github_com_octohelm_storage_pkg_sqlpipe.OperatorType {
	return github_com_octohelm_storage_pkg_sqlpipe.OperatorFilter
}

func (f *UserByCreatedAt) Next(src github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User] {
	return src.Pipe(github_com_octohelm_storage_pkg_sqlpipe_filter.AsWhere(github_com_octohelm_storage_testdata_model.UserT.CreatedAt, f.CreatedAt))
}

func (f *UserByCreatedAt) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.CreatedAt, f.CreatedAt)
}

type UserByDeletedAt struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.User]

	// 按  筛选
	DeletedAt *github_com_octohelm_storage_pkg_filter.Filter[int64] `name:"user~deletedAt,omitempty" in:"query"`
}

func (f *UserByDeletedAt) OperatorType() github_com_octohelm_storage_pkg_sqlpipe.OperatorType {
	return github_com_octohelm_storage_pkg_sqlpipe.OperatorFilter
}

func (f *UserByDeletedAt) Next(src github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User]) github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.User] {
	return src.Pipe(github_com_octohelm_storage_pkg_sqlpipe_filter.AsWhere(github_com_octohelm_storage_testdata_model.UserT.DeletedAt, f.DeletedAt))
}

func (f *UserByDeletedAt) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.UserT.DeletedAt, f.DeletedAt)
}

type OrgByID struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.Org]

	// 按  筛选
	ID *github_com_octohelm_storage_pkg_filter.Filter[github_com_octohelm_storage_testdata_model.OrgID] `name:"org~id,omitempty" in:"query"`
}

func (f *OrgByID) OperatorType() github_com_octohelm_storage_pkg_sqlpipe.OperatorType {
	return github_com_octohelm_storage_pkg_sqlpipe.OperatorFilter
}

func (f *OrgByID) Next(src github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.Org]) github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.Org] {
	return src.Pipe(github_com_octohelm_storage_pkg_sqlpipe_filter.AsWhere(github_com_octohelm_storage_testdata_model.OrgT.ID, f.ID))
}

func (f *OrgByID) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.OrgT.ID, f.ID)
}

type OrgByName struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.Org]

	// 按  筛选
	Name *github_com_octohelm_storage_pkg_filter.Filter[string] `name:"org~name,omitempty" in:"query"`
}

func (f *OrgByName) OperatorType() github_com_octohelm_storage_pkg_sqlpipe.OperatorType {
	return github_com_octohelm_storage_pkg_sqlpipe.OperatorFilter
}

func (f *OrgByName) Next(src github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.Org]) github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.Org] {
	return src.Pipe(github_com_octohelm_storage_pkg_sqlpipe_filter.AsWhere(github_com_octohelm_storage_testdata_model.OrgT.Name, f.Name))
}

func (f *OrgByName) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.OrgT.Name, f.Name)
}

type OrgByCreatedAt struct {
	github_com_octohelm_storage_pkg_dal_compose.From[github_com_octohelm_storage_testdata_model.Org]

	// 按  筛选
	CreatedAt *github_com_octohelm_storage_pkg_filter.Filter[github_com_octohelm_storage_pkg_datatypes.Datetime] `name:"org~createdAt,omitempty" in:"query"`
}

func (f *OrgByCreatedAt) OperatorType() github_com_octohelm_storage_pkg_sqlpipe.OperatorType {
	return github_com_octohelm_storage_pkg_sqlpipe.OperatorFilter
}

func (f *OrgByCreatedAt) Next(src github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.Org]) github_com_octohelm_storage_pkg_sqlpipe.Source[github_com_octohelm_storage_testdata_model.Org] {
	return src.Pipe(github_com_octohelm_storage_pkg_sqlpipe_filter.AsWhere(github_com_octohelm_storage_testdata_model.OrgT.CreatedAt, f.CreatedAt))
}

func (f *OrgByCreatedAt) ApplyQuerier(q github_com_octohelm_storage_pkg_dal.Querier) github_com_octohelm_storage_pkg_dal.Querier {
	return github_com_octohelm_storage_pkg_dal_compose.ApplyQuerierFromFilter(q, github_com_octohelm_storage_testdata_model.OrgT.CreatedAt, f.CreatedAt)
}
