// Code generated by gengo:runtimedoc DO NOT EDIT.
package time

func (v *CreationModificationTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{
				"更新时间",
			}, true
		}
		if doc, ok := runtimeDoc(&v.CreationTime, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"定义同时包含创建和更新时间的通用结构。",
	}, true
}

func (v *CreationTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{
				"创建时间",
			}, true
		}

		return nil, false
	}
	return []string{
		"定义带创建时间字段的通用结构。",
	}, true
}

func (v *CreationUpdationDeletionTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{
				"删除时间",
			}, true
		}
		if doc, ok := runtimeDoc(&v.CreationUpdationTime, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"定义带软删除时间的通用结构。",
	}, true
}

func (*Duration) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"表示可序列化、可扫描的时长值。",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
