/*
Package time GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package time

import (
	_ "embed"
)

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v *CreationModificationTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{
				"更新时间",
			}, true
		}
		if doc, ok := runtimeDoc(&v.CreationTime, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v *CreationTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{
				"创建时间",
			}, true
		}

		return nil, false
	}
	return []string{}, true
}

func (v *CreationUpdationDeletionTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{
				"删除时间",
			}, true
		}
		if doc, ok := runtimeDoc(&v.CreationUpdationTime, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}
