/*
Package sqlfrag GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package sqlfrag

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (Const) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (Func) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (NamedArgSet) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (Values) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
