/*
Package columndef GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package columndef

import _ "embed"

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v *ColumnDef) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Type":
			return []string{}, true
		case "DataType":
			return []string{}, true
		case "Length":
			return []string{}, true
		case "Decimal":
			return []string{}, true
		case "Default":
			return []string{}, true
		case "OnUpdate":
			return []string{}, true
		case "Null":
			return []string{}, true
		case "AutoIncrement":
			return []string{}, true
		case "DeprecatedActions":
			return []string{}, true
		case "Comment":
			return []string{}, true
		case "Description":
			return []string{}, true
		case "Relation":
			return []string{}, true
		case "StructTag":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *DeprecatedActions) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "RenameTo":
			return []string{}, true
		}

		return nil, false
	}
	return []string{}, true
}
