package tablegen

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/octohelm/gengo/pkg/gengo"
	"github.com/octohelm/gengo/pkg/gengo/testingutil"
	. "github.com/octohelm/x/testing/v2"
)

func newTestingModule(t *testing.T, files map[string]string) *testingutil.Module {
	t.Helper()

	m := MustValue(t, func() (*testingutil.Module, error) {
		return testingutil.NewModule(t, files)
	})

	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatalf("无法定位测试文件路径")
	}

	root := filepath.Clean(filepath.Join(filepath.Dir(filename), "../.."))
	goMod := filepath.Join(m.Dir, "go.mod")
	data := MustValue(t, func() ([]byte, error) {
		return os.ReadFile(goMod)
	})

	extra := strings.Join([]string{
		"",
		"require github.com/octohelm/storage v0.0.0",
		"",
		"replace github.com/octohelm/storage => " + root,
		"",
	}, "\n")

	Must(t, func() error {
		return os.WriteFile(goMod, append(data, []byte(extra)...), 0o644)
	})

	return m
}

func TestTableGen(t *testing.T) {
	m := newTestingModule(t, map[string]string{
		"sample/types.go": `package sample

var ModelRegistry registry

type registry struct{}

func (registry) Add(v any) {}

// 用户
// +gengo:table
// +gengo:table:register=ModelRegistry
// +gengo:table:objectkind=user
// @def primary ID
// @def unique_index i_name Name DeletedAt
// @def index i_created_at CreatedAt,desc
type User struct {
	// 用户ID
	ID uint64 ` + "`" + `db:"f_id,autoincrement"` + "`" + `
	// 姓名
	Name string ` + "`" + `db:"f_name,size=255,default=''" sortable:"true"` + "`" + `
	CreatedAt int64 ` + "`" + `db:"f_created_at,default='0'"` + "`" + `
	DeletedAt int64 ` + "`" + `db:"f_deleted_at,default='0'"` + "`" + `
	Ignored string ` + "`" + `db:"-"` + "`" + `
}
`,
	})

	files := MustValue(t, func() (map[string]string, error) {
		return m.Generate(gengo.GeneratorArgs{
			Entrypoint:         []string{m.ImportPath("sample")},
			OutputFileBaseName: "zz_generated_test",
			Force:              true,
		}, &tableGen{})
	})

	Then(
		t, "应生成 table 静态定义和索引入口",
		Expect(files, Be(testingutil.File(
			"sample/zz_generated_test.table.go",
			testingutil.Contains(
				"Code generated by gengo:table DO NOT EDIT.",
				"func init() {",
				"ModelRegistry.Add(UserT)",
				`func (User) GetKind() string {`,
				`return "user"`,
				`func (User) TableName() string {`,
				`return "t_user"`,
				`func (User) PrimaryKey() []string {`,
				`func (User) UniqueIndexes() sqlbuilder.Indexes {`,
				`func (User) Indexes() sqlbuilder.Indexes {`,
				"// 用户ID",
				"ID modelscoped.TypedColumn[User, uint64]",
				"Name modelscoped.TypedColumn[User, string]",
				"Primary modelscoped.Key[User]",
				"IName   modelscoped.Key[User]",
				`CastTypedColumn[User, string](modelscoped.FromModel[User]().F("Name"))`,
			),
			testingutil.NotContains("Ignored modelscoped.TypedColumn"),
		))),
	)
}

func TestTableGenSkipUnexported(t *testing.T) {
	m := newTestingModule(t, map[string]string{
		"sample/types.go": `package sample

// +gengo:table
// @def primary ID
type hidden struct {
	ID uint64 ` + "`" + `db:"f_id,autoincrement"` + "`" + `
}
`,
	})

	files := MustValue(t, func() (map[string]string, error) {
		return m.Generate(gengo.GeneratorArgs{
			Entrypoint:         []string{m.ImportPath("sample")},
			OutputFileBaseName: "zz_generated_test",
			Force:              true,
		}, &tableGen{})
	})

	Then(
		t, "未导出类型会被静默跳过且不生成文件",
		Expect(len(files), Equal(0)),
	)
}
