package filtergen

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/octohelm/gengo/pkg/gengo"
	"github.com/octohelm/gengo/pkg/gengo/testingutil"
	. "github.com/octohelm/x/testing/v2"
)

func newTestingModule(t *testing.T, files map[string]string) *testingutil.Module {
	t.Helper()

	m := MustValue(t, func() (*testingutil.Module, error) {
		return testingutil.NewModule(t, files)
	})

	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatalf("无法定位测试文件路径")
	}

	root := filepath.Clean(filepath.Join(filepath.Dir(filename), "../.."))
	goMod := filepath.Join(m.Dir, "go.mod")
	data := MustValue(t, func() ([]byte, error) {
		return os.ReadFile(goMod)
	})

	extra := strings.Join([]string{
		"",
		"require github.com/octohelm/storage v0.0.0",
		"",
		"replace github.com/octohelm/storage => " + root,
		"",
	}, "\n")

	Must(t, func() error {
		return os.WriteFile(goMod, append(data, []byte(extra)...), 0o644)
	})

	return m
}

func TestFilteropGen(t *testing.T) {
	m := newTestingModule(t, map[string]string{
		"sample/types.go": `package sample

// +gengo:table
// @def primary ID
// @def unique_index i_name Name
// @def index i_display_name DisplayName
type User struct {
	// 用户ID
	ID uint64 ` + "`" + `db:"f_id,autoincrement"` + "`" + `
	// 姓名
	Name string ` + "`" + `db:"f_name,size=255,default=''"` + "`" + `
	// 显示名
	DisplayName string ` + "`" + `db:"f_display_name,size=255,default=''" json:"displayName" sortable:"true"` + "`" + `
}

// +gengo:table
// @def primary ID
// @def unique_index i_code Code
type Team struct {
	ID uint64 ` + "`" + `db:"f_id,autoincrement"` + "`" + `
	Code string ` + "`" + `db:"f_code,size=255,default=''"` + "`" + `
}

// +gengo:table
// @def primary ID
// @def unique_index i_title Title
type AuditLog struct {
	ID uint64 ` + "`" + `db:"f_id,autoincrement"` + "`" + `
	Title string ` + "`" + `db:"f_title,size=255,default=''"` + "`" + `
}

// +gengo:filterop
type FilterSet struct {
	User
	Team ` + "`" + `of:"org"` + "`" + `
	AuditLog ` + "`" + `select:"true"` + "`" + `
}
`,
	})

	files := MustValue(t, func() (map[string]string, error) {
		return m.Generate(gengo.GeneratorArgs{
			Entrypoint:         []string{m.ImportPath("sample")},
			OutputFileBaseName: "zz_generated_test",
			Force:              true,
		}, &filteropGen{})
	})

	Then(
		t, "应按索引字段生成过滤器和排序器",
		Expect(files, Be(testingutil.File(
			"sample/zz_generated_test.filterop.go",
			testingutil.Contains(
				"Code generated by gengo:filterop DO NOT EDIT.",
				"type UserByID struct",
				`ID *filter.Filter[uint64] `+"`"+`name:"user~id,omitzero" in:"query"`+"`",
				"type UserByName struct",
				`Name *filter.Filter[string] `+"`"+`name:"user~name,omitzero" in:"query"`+"`",
				"type UserByDisplayName struct",
				`DisplayName *filter.Filter[string] `+"`"+`name:"user~displayName,omitzero" in:"query"`+"`",
				"type UserSortByDisplayName struct",
				`return "user~displayName"`,
				`return "显示名"`,
				"type OrgTeamByCode struct",
				`Code *filter.Filter[string] `+"`"+`name:"org~code,omitzero" in:"query"`+"`",
			),
			testingutil.NotContains(
				"type AuditLogByTitle struct",
				"type TeamSortByCode struct",
			),
		))),
	)
}
