/*
Package directive GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package directive

import _ "embed"

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v *Directive) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Args":
			return []string{}, true
		case "Name":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *ErrInvalidDirective) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DirectiveName":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *ErrUnsupportedDirective) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DirectiveName":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (*Kind) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (*Newer) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (*RawValue) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (*UnmarshalerFunc) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
