/*
Package structs GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package structs

import (
	_ "embed"
)

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v *Field) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "FieldName":
			return []string{}, true
		case "Type":
			return []string{}, true
		case "Field":
			return []string{}, true
		case "Tags":
			return []string{}, true
		case "Loc":
			return []string{}, true
		case "ModelLoc":
			return []string{}, true
		case "ColumnType":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *FieldValue) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Field":
			return []string{}, true
		case "TableName":
			return []string{}, true
		case "Value":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
