/*
Package datatypes GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package datatypes

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (Bool) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (SFID) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"openapi:strfmt snowflake-id",
	}, true
}
func (SFIDs) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
