# 列出 Go 工具链入口
[group('meta')]
default:
    @just --list --unsorted

# 整理依赖
[group('env')]
[no-cd]
dep:
    go mod tidy

# 运行全部测试
[group('test')]
[no-cd]
test *args:
    CGO_ENABLED=1 go test {{ args }} -count=1 -failfast ./...

# 格式化
[group('fmt')]
[no-cd]
fmt path='./...':
    go fix {{ path }}
    go tool fmt {{ path }}

# 更新依赖
[group('env')]
[no-cd]
update path='./...':
    go get -u {{ path }}

# 代码生成
[group('build')]
[no-cd]
gen:
    go generate -v ./...
    go generate -v ./testdata/model/...

# 安装 agent skills
[group('env')]
[no-cd]
skills-install:
    go tool skills-install
